In [1]:
import numpy as np

In [2]:
array=[1,2,3,4,5]

In [6]:
array=np.array(array)  #  将list对象转换成数组
array2=array+1 

In [7]:
array+array2

array([ 3,  5,  7,  9, 11])

In [11]:
array.shape

(5,)

In [9]:
type(array)

numpy.ndarray

In [14]:
array.itemsize #有多少个元素

8

In [15]:
array

array([1, 2, 3, 4, 5])

In [16]:
t_array=np.arange(0,100,10) #等距生成数据
t_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [18]:
random_array=np.random.rand(10)
random_array

array([0.90091591, 0.31865674, 0.8012314 , 0.84767242, 0.05464666,
       0.95088306, 0.33056121, 0.25557699, 0.90511166, 0.25059761])

In [19]:
random_array>0.5

array([ True, False,  True,  True, False,  True, False, False,  True,
       False])

In [20]:
np.where(random_array>0.5)

(array([0, 2, 3, 5, 8]),)